--Day 48 
--1.Total Revenu : Find totale Revenue 
select 
	sum(cp.payment_amount )
from  cleaned_payments cp;

--2.Total Revenu by date  : 
select
	cp.payment_date ,
	sum(cp.payment_amount )
from  cleaned_payments cp
group by cp.payment_date
order by cp.payment_date ;

--3.Total Revenu by Month  : 
select
	extract(month from cp.payment_date ) as month,
	to_char(cp.payment_date,'month') as month_name,
	sum(cp.payment_amount )
from  cleaned_payments cp
group by month,month_name
order by month_name ;

--4.Revenu by product : Find revenue generated by each product
select 
	cp.product_id, 
	cp.product_name ,
	--cod.quantity ,
	--cp2.payment_amount,
	sum(cod.quantity *cp2.payment_amount ) as total_revenue
from cleaned_products cp
join cleaned_order_details cod 
	on cp.product_id =cod.product_id 
join cleaned_payments cp2 
    on cod.order_id =cp2.order_id 
group by cp.product_id ,cp.product_name 
order by total_revenue desc ;

--5. Revenu by customer  : Find revenue generated by each customer
select 
	cc.customer_id , 
	cc.customer_name  ,
	--cod.quantity ,
	--cp2.payment_amount,
	sum(cod.quantity *cp2.payment_amount ) as total_revenue
from cleaned_customers cc 
join cleaned_orders co 
	on cc.customer_id =co.customer_id  
join cleaned_order_details cod 
	on co.order_id  =cod.order_id  
join cleaned_payments cp2 
    on cod.order_id =cp2.order_id 
group by cc.customer_id , cc.customer_name  
order by total_revenue desc ;

--5 find category wise revenue 
select 
	cp.product_id ,
	cp.product_name ,
	sum(cod.quantity *cp2.payment_amount ) as toatl_revenu
from cleaned_products cp
join cleaned_order_details cod 
	on cp.product_id =cod.product_id 
join cleaned_payments cp2 
	on cod.order_id =cp2.order_id 
group by 	cp.product_id ,cp.product_name 
order by toatl_revenu desc;
	
--7 . Hig revenue Date : Find the Day generated hihest trend 
 
select
	cp.payment_date,
	sum(cp.payment_amount) as total_revenu_by_date
from  cleaned_payments cp
group by cp.payment_date
order by cp.payment_date ;